### ISSUE TITLE
setBeanNames参数是可以传递多个字符串

### ISSUE THREAD

**Issue by mycoco2014** [yujunhao8831/spring-boot-mybatisplus-multiple-datasource#1]
beanNameAutoProxyCreator.setBeanNames( defaultTransactionBeanNameSuffix );
参数是一次传递多个字符串,而不能调用多次,如果调用多次,会出现最后赋值的把之前的覆盖掉. 

*Service, *ServiceImpl,
如果执行了2次setBeanNames, 则只有*ServiceImpl规则生效, *Service规则则不会生效

**Comment by yujunhao8831** [comment]
![3834823a-5958-42fb-95cc-917449cfbcae](https://user-images.githubusercontent.com/12233421/31307340-241c55f8-ab28-11e7-854f-b2443f8239bf.png)

**Comment by yujunhao8831** [comment]
<img width="1444" alt="qq20171007-193029 2x" src="https://user-images.githubusercontent.com/12233421/31307381-145b6e00-ab29-11e7-9917-29b935adb592.png">

**Comment by mycoco2014** [comment]
在第一步this.beanNames  = new ArrayList的时候,原来的应该是被清空了的把.
测试你的代码,如果 *Service,*ServiceImpl位置颠倒,则Service后缀的会被拦截掉,
两个好像不能同时生效, :)

**Comment by yujunhao8831** [comment]
这个问题已经改好了
